### PR TITLE
Fixed Argument 2 passed to Contributte\FormMultiplier\ComponentResolver::__construct() must be of the type array, object given

### PR DESCRIPTION
**Pull request by martenb**
Fixed Argument 2 passed to Contributte\FormMultiplier\ComponentResolver::__construct() must be of the type array, object given

### CODE REVIEW

**Comment by diegosardina** [comment]
A bit more words? Maybe you are using ->setMappedType() in your form?

**Comment by martenb** [comment]
No, i'm not. This error occurs, when i click on add (createButton). I have nested multiplier. This is, how $this->createContainer()->getValues() looks like

image

**Comment by diegosardina** [comment]
>
> I have nested multiplier.
> 

I got it.

At the beginning I wasn't able to reproduce the problem because nesting of multipliers didn't work. I had to use this work-around for the add button: https://forum.nette.org/cs/31918-zanoreny-multiplier-v-dalsim-multiplieru

Unfortunately this component looks unmaintained :-(

**Comment by martenb** [comment]
Ok, maybe i was not clear. Everything Is working fine with this fix..

**Comment by martenb** [comment]
Do you need some more informations?

**Comment by martenb** [comment]
Any news about merging the fix?

**Comment by diegosardina** [comment]
I guess this component is not currently maintained (I have also two PRs pending).

This is very unfortunate because this component is really useful

**Comment by petrparolek** [comment]
ping @MartkCz

**Comment by martenb** [comment]
ping @f3l1x

**Comment by f3l1x** [comment]
Hi guys. Could you please, at least, add some tests? I am not using this pkg, so it's blackbox for me. If you want to merge from me, I need some assurance. Yep?

**Comment by martenb** [comment]
> Hi guys. Could you please, at least, add some tests? I am not using this pkg, so it's blackbox for me. If you want to merge from me, I need some assurance. Yep?

This is problem, because it works well in tests. Here is a test, which work
https://github.com/contributte/forms-multiplier/blob/master/tests/unit/MultiplierTest.php#L215

But nette sets defaults as ArrayHash, not array and this is the problem, which i fixed up.

**Comment by martenb** [comment]
Similar problem #53

**Comment by martenb** [comment]
ping @f3l1x

**Comment by f3l1x** [comment]
Merged. Thanks.

**Pull request merged**
